class FastTools(object):
    @staticmethod
    def read_json():...
    @staticmethod
    def write_json():...
    @staticmethod
    def read_txt():...
    @staticmethod
    def write_txt():...
    @staticmethod
    def read_jsonl():...
    @staticmethod
    def write_jsonl():...
    @staticmethod
    def read_yaml():...
    @staticmethod
    def write_yaml():...